name: Linux Integration Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        go-version: ["1.18", "1.19", "1.20"]
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Load the vhost_vsock kernel module
        run: sudo modprobe vhost_vsock

      - name: Change the permissions of /dev/vsock for integration tests
        run: sudo chmod 666 /dev/vsock

      - name: Run integration tests
        run: go test -v -race -run TestIntegration ./...
